# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_email_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAttachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_book', models.FileField(upload_to='/home/dvm/bosm/bosm2016/static/documents/rules.pdf')),
            ],
        ),
    ]
