# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_emailattachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailattachments',
            name='rule_book',
            field=models.FileField(upload_to='/home/dvm/bosm/bosm2016/static/documents/rules.txt'),
        ),
    ]
